-- Seed data for The AI Work App

insert into public.courses_library (
  title,
  source,
  source_url,
  duration_weeks,
  difficulty_level,
  description,
  mbti_fit,
  tki_fit,
  skills,
  prerequisites,
  why_for_mbti
)
values
  (
    'Human Skills in the Age of AI',
    'linkedin',
    'https://www.linkedin.com/learning/human-skills-in-the-age-of-ai',
    3,
    'beginner',
    'Human-centered skills to thrive alongside AI.',
    '["ENFP","ESFJ","ISFJ"]'::jsonb,
    '["collaborating","accommodating"]'::jsonb,
    '["communication","leadership","empathy"]'::jsonb,
    '[]'::jsonb,
    '{"ENFP":"Channel your creativity into people-first leadership.","ESFJ":"Strengthen your collaboration toolkit for teams.","ISFJ":"Build confidence navigating change with AI."}'::jsonb
  ),
  (
    'Career Essentials in Generative AI',
    'linkedin',
    'https://www.linkedin.com/learning/career-essentials-in-generative-ai',
    4,
    'beginner',
    'Practical fundamentals of generative AI for career growth.',
    '["INTJ","INTP","ENTJ"]'::jsonb,
    '["competing","collaborating"]'::jsonb,
    '["prompting","workflows","ai basics"]'::jsonb,
    '[]'::jsonb,
    '{"INTJ":"A structured overview to sharpen your AI strategy.","INTP":"Feed your curiosity with clear foundations.","ENTJ":"Turn AI literacy into execution advantage."}'::jsonb
  ),
  (
    'AI for Organizational Leaders',
    'linkedin',
    'https://www.linkedin.com/learning/ai-for-organizational-leaders',
    5,
    'intermediate',
    'Leadership decisions, governance, and AI adoption.',
    '["ENTJ","ESTJ","INTJ"]'::jsonb,
    '["competing","collaborating"]'::jsonb,
    '["strategy","governance","change management"]'::jsonb,
    '[]'::jsonb,
    '{"ENTJ":"Lead adoption with decisive strategy.","ESTJ":"Operationalize AI with clear governance.","INTJ":"Map AI to long-term organizational advantage."}'::jsonb
  ),
  (
    'AI for Managers',
    'linkedin',
    'https://www.linkedin.com/learning/ai-for-managers',
    5,
    'beginner',
    'Use AI to manage teams, projects, and priorities.',
    '["ESFJ","ENFJ","ESTJ"]'::jsonb,
    '["collaborating","competing"]'::jsonb,
    '["team leadership","prioritization","tools"]'::jsonb,
    '[]'::jsonb,
    '{"ESFJ":"Blend people-first management with modern AI tools.","ENFJ":"Scale your coaching impact with AI.","ESTJ":"Add AI efficiency to your execution system."}'::jsonb
  ),
  (
    'Microsoft Copilot for Productivity',
    'linkedin',
    'https://www.linkedin.com/learning/microsoft-copilot-for-productivity',
    3,
    'beginner',
    'Hands-on Copilot workflows for daily productivity.',
    '["ISTJ","INTJ","ESFJ","ISFJ"]'::jsonb,
    '["competing","collaborating","compromising","avoiding","accommodating"]'::jsonb,
    '["productivity","microsoft","automation"]'::jsonb,
    '[]'::jsonb,
    '{"ISTJ":"Turn repeatable work into automated routines.","INTJ":"Systematize knowledge work with Copilot.","ESFJ":"Support your team with faster outputs.","ISFJ":"Reduce friction in everyday tasks."}'::jsonb
  ),
  (
    'Productivity with Generative AI',
    'linkedin',
    'https://www.linkedin.com/learning/productivity-with-generative-ai',
    4,
    'beginner',
    'Build lightweight systems for AI-powered work.',
    '["ENFP","ENTP","ENTJ"]'::jsonb,
    '["competing","collaborating"]'::jsonb,
    '["automation","prompting","systems"]'::jsonb,
    '[]'::jsonb,
    '{"ENFP":"Turn ideas into repeatable outputs.","ENTP":"Experiment with workflows that compound.","ENTJ":"Scale execution with AI leverage."}'::jsonb
  ),
  (
    'Microsoft Azure AI Essentials',
    'linkedin',
    'https://www.linkedin.com/learning/microsoft-azure-ai-essentials',
    5,
    'intermediate',
    'Core Azure AI services and concepts.',
    '["INTP","INTJ","ENTP","ISTP"]'::jsonb,
    '["competing","collaborating"]'::jsonb,
    '["cloud","ml","azure"]'::jsonb,
    '[]'::jsonb,
    '{"INTP":"Explore AI systems with real cloud primitives.","INTJ":"Translate strategy into architecture.","ENTP":"Prototype quickly using platform tools.","ISTP":"Build practical AI skills through doing."}'::jsonb
  ),
  (
    'Microsoft Security Essentials',
    'linkedin',
    'https://www.linkedin.com/learning/microsoft-security-essentials',
    4,
    'beginner',
    'Security fundamentals for Microsoft ecosystems.',
    '["ISTJ","INTJ","ESTJ"]'::jsonb,
    '["competing"]'::jsonb,
    '["security","microsoft","risk"]'::jsonb,
    '[]'::jsonb,
    '{"ISTJ":"Hard skills for protecting systems you run.","INTJ":"Build a risk model with practical controls.","ESTJ":"Create operational security discipline."}'::jsonb
  ),
  (
    'Career Essentials in Cybersecurity',
    'linkedin',
    'https://www.linkedin.com/learning/career-essentials-in-cybersecurity',
    3,
    'beginner',
    'Start a cybersecurity foundation with practical pathways.',
    '["INTJ","INTP","ISTJ"]'::jsonb,
    '["competing"]'::jsonb,
    '["security","threats","fundamentals"]'::jsonb,
    '[]'::jsonb,
    '{"INTJ":"A clear map of the cybersecurity landscape.","INTP":"Conceptual breadth with clear terminology.","ISTJ":"Concrete steps into security workflows."}'::jsonb
  ),
  (
    'Career Essentials in Sustainable Tech',
    'linkedin',
    'https://www.linkedin.com/learning/career-essentials-in-sustainable-tech',
    3,
    'beginner',
    'Sustainability concepts and modern tech roles.',
    '["ENFP","INFP","ESFJ"]'::jsonb,
    '["collaborating","accommodating"]'::jsonb,
    '["sustainability","tech","impact"]'::jsonb,
    '[]'::jsonb,
    '{"ENFP":"Align purpose with real skills.","INFP":"Explore impact-driven tech paths.","ESFJ":"Lead community-first sustainability initiatives."}'::jsonb
  ),
  (
    'Career Essentials in Data Analysis',
    'linkedin',
    'https://www.linkedin.com/learning/career-essentials-in-data-analysis',
    4,
    'beginner',
    'Core data analysis workflows and thinking.',
    '["INTP","INTJ","ISTP","ISTJ"]'::jsonb,
    '["competing","collaborating"]'::jsonb,
    '["data","analysis","excel"]'::jsonb,
    '[]'::jsonb,
    '{"INTP":"Turn curiosity into structured analysis.","INTJ":"Build a clear analytical toolkit.","ISTP":"Hands-on patterns for solving problems.","ISTJ":"Reliable workflows for clean reporting."}'::jsonb
  ),
  (
    'Career Essentials in Business Analysis',
    'linkedin',
    'https://www.linkedin.com/learning/career-essentials-in-business-analysis',
    4,
    'beginner',
    'Stakeholder needs, requirements, and analysis tools.',
    '["ENTJ","ESTJ","ENFJ"]'::jsonb,
    '["collaborating","competing"]'::jsonb,
    '["requirements","stakeholders","analysis"]'::jsonb,
    '[]'::jsonb,
    '{"ENTJ":"Drive clarity and decisions with better analysis.","ESTJ":"Operationalize requirements efficiently.","ENFJ":"Align people and outcomes through insight."}'::jsonb
  ),
  (
    'Career Essentials in Software Development',
    'linkedin',
    'https://www.linkedin.com/learning/career-essentials-in-software-development',
    4,
    'beginner',
    'Foundations of software engineering and workflows.',
    '["INTP","INTJ","ISTP"]'::jsonb,
    '["competing"]'::jsonb,
    '["software","engineering","git"]'::jsonb,
    '[]'::jsonb,
    '{"INTP":"Conceptual clarity meets practical systems.","INTJ":"A structured path into engineering.","ISTP":"Learn by building and iterating."}'::jsonb
  ),
  (
    'Career Essentials in Project Management',
    'linkedin',
    'https://www.linkedin.com/learning/career-essentials-in-project-management',
    4,
    'beginner',
    'Project basics: scope, stakeholders, delivery.',
    '["ESTJ","ENTJ","ESFJ"]'::jsonb,
    '["competing","collaborating"]'::jsonb,
    '["planning","execution","delivery"]'::jsonb,
    '[]'::jsonb,
    '{"ESTJ":"Turn plans into predictable delivery.","ENTJ":"Build leverage through strong execution.","ESFJ":"Keep teams aligned and moving."}'::jsonb
  ),
  (
    'Career Essentials in Systems Administration',
    'linkedin',
    'https://www.linkedin.com/learning/career-essentials-in-systems-administration',
    4,
    'beginner',
    'Practical systems administration and operations.',
    '["ISTJ","INTJ","ISTP","INTP"]'::jsonb,
    '["competing"]'::jsonb,
    '["systems","ops","reliability"]'::jsonb,
    '[]'::jsonb,
    '{"ISTJ":"Build disciplined operational habits.","INTJ":"Learn systems from first principles.","ISTP":"Hands-on troubleshooting skills.","INTP":"Understand systems architecture and practice."}'::jsonb
  ),
  (
    'Digital Literacy and Productivity',
    'linkedin',
    'https://www.linkedin.com/learning/digital-literacy-and-productivity',
    3,
    'beginner',
    'Digital fundamentals for modern work.',
    '["ISFJ","ESFJ","ISTJ"]'::jsonb,
    '["accommodating","collaborating"]'::jsonb,
    '["digital","workflow","productivity"]'::jsonb,
    '[]'::jsonb,
    '{"ISFJ":"Calm, clear workflows for daily work.","ESFJ":"Improve how you coordinate and communicate.","ISTJ":"Sharpen your productivity baseline."}'::jsonb
  ),
  (
    'Emotional Intelligence in Leadership',
    'linkedin',
    'https://www.linkedin.com/learning/emotional-intelligence-in-leadership',
    2,
    'beginner',
    'EQ, empathy, and leadership communication.',
    '["ENFP","ENFJ","ESFJ","INFP"]'::jsonb,
    '["collaborating","accommodating"]'::jsonb,
    '["emotional intelligence","leadership"]'::jsonb,
    '[]'::jsonb,
    '{"ENFP":"Channel warmth into leadership.","ENFJ":"Refine coaching and influence.","ESFJ":"Strengthen relationships with clarity.","INFP":"Lead with calm confidence."}'::jsonb
  ),
  (
    'Critical Thinking & Decision Making',
    'linkedin',
    'https://www.linkedin.com/learning/critical-thinking-and-decision-making',
    2,
    'beginner',
    'Decision frameworks and critical thinking habits.',
    '["INTJ","INTP","ENTJ","ENTP"]'::jsonb,
    '["competing","collaborating"]'::jsonb,
    '["decision making","critical thinking"]'::jsonb,
    '[]'::jsonb,
    '{"INTJ":"Improve decision quality with clear frameworks.","INTP":"Sharpen analysis with structured thinking.","ENTJ":"Make decisions faster with fewer errors.","ENTP":"Turn debate into crisp outcomes."}'::jsonb
  ),
  (
    'Effective Communication for Managers',
    'linkedin',
    'https://www.linkedin.com/learning/effective-communication-for-managers',
    3,
    'beginner',
    'Communication skills for modern managers.',
    '["ENFJ","ESFJ","ENFP","ESFP"]'::jsonb,
    '["collaborating","accommodating"]'::jsonb,
    '["communication","leadership"]'::jsonb,
    '[]'::jsonb,
    '{"ENFJ":"Increase clarity without losing warmth.","ESFJ":"Build stronger alignment across teams.","ENFP":"Communicate vision with structure.","ESFP":"Make feedback simple and actionable."}'::jsonb
  ),
  (
    'Learning to Learn: Develop Self-Directed Skills',
    'linkedin',
    'https://www.linkedin.com/learning/learning-to-learn-develop-self-directed-skills',
    2,
    'beginner',
    'Meta-learning, habits, and self-directed systems.',
    '["INFP","INTP","INTJ","INFJ"]'::jsonb,
    '["collaborating","competing"]'::jsonb,
    '["learning","habits","systems"]'::jsonb,
    '[]'::jsonb,
    '{"INFP":"Turn values into consistent learning habits.","INTP":"Build systems that match your curiosity.","INTJ":"Design a durable learning system.","INFJ":"Learn deeply without burnout."}'::jsonb
  )
;

insert into public.badges (name, description, icon_emoji, requirement, points_reward)
values
  ('First Step', 'Complete your first assessment set (MBTI + TKI).', '🚀', '{"type":"assessments_completed","value":1}', 50),
  ('Course Starter', 'Create your first learning path.', '📖', '{"type":"learning_paths","value":1}', 50),
  ('Learning Scholar', 'Complete 3 courses.', '🎓', '{"type":"courses_completed","value":3}', 100),
  ('Note Master', 'Write 20 notes.', '📝', '{"type":"notes_created","value":20}', 50),
  ('AI Enthusiast', 'Use AI tools 50+ times.', '✨', '{"type":"ai_uses","value":50}', 50),
  ('Consistent Learner', 'Hit a 7-day streak.', '🔥', '{"type":"streak","value":7}', 50),
  ('Knowledge Seeker', 'Reach 500 points.', '🧠', '{"type":"points","value":500}', 50),
  ('Team Player', 'Share 5 achievements.', '👥', '{"type":"shares","value":5}', 50),
  ('Speed Learner', 'Complete a course in under 2 weeks.', '⚡', '{"type":"fast_course","value":1}', 50),
  ('Legendary', 'Reach 1000 points.', '👑', '{"type":"points","value":1000}', 100)
on conflict (name) do nothing;
